language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install:
- npm install express mocha supertest chai
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: gKTvRGRHB7YglLuuxNnkbxfpg4b685jMRpnumNLqdPTGnHyjsfdsqLAjKiOGBzmQ/GWjWSXeOtlPFdcYPyOvqNl2UCrwHG3acCQbxxK8/xLLUoERmfPVTddEaGgP8lI8iieJLLHlFDyjRy0lJtDz/zvFlqLga9QRMcSGYWhtAXlc/AZ9wAspjmViav0FijvEsaIfwDZk3kwTb+e+8WlTc+5iUsG3I4r6HI387b6v/oOPeMd9Hr275vujJl9q5ZE3ZYGu2PGgkgmqm40CAQA7eO0jvCIUu3J3Leq3x89LqJM+chzxEEnz7UHqh/whitVL6Xm+XffojmpTKgM6eePDPYrYOgguRNT9ZzfbSRJ/MfyJ+iTegv64Sm7Zk9iWnECWoIWLABZEhlRD1He5ZIVkGSaP9SsF0O5WQUxpB1cYxHelmhqF+VxJI5raimgnEKFcWRphGMlqGxtxr9TK9rhXGyyX4IiIAHrLQfXWwEEiP2Vu1dnqgstevro5ZVd9dp1Jr70oCRnW0ushT92N4zB0/MjjV0wLGzFyXW39Rx1uy1LxqBtRYZDq9QcVgVK1UQzo9cClamYq4+eCmknG5h7K1aC8qlqfm2O+QPKd1oGT1xNctlOO4zjvbi820lkRM+wyDE0BRSxZAuNlV/LhFhnp4Uysfk1UEsfHdlzTgU5J740=
  app: iswapp
  on:
    repo: NicoRomero3210/SwIC
addons:
  sonarcloud: true
script:
  - npm run test
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=nicoromero3210-github -Dsonar.projectKey=NicoRomero3210_SwIC -Dsonar.sources='./src' -X
notifications:
    webhooks: https://travis-for-jira-prod.toolsplus.app/travis/notifications?token=6c235402-b579-3021-9194-b95541842111
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always