language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install:
- npm install express mocha supertest chai
script:
- npm run test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: AAmnCgUM7BXMDzvMp4y9En2xsFhm1scJJd/sRr3MbPpglzy2AK/muwG10tiCgaZbl3tkrDXuXLatpraJhtrsAcPgtIwYVqOXXs++FHjTDkim0281XVEGBaOsZ2qutlHmPcmyKsIV+T+qCaN4znW6NIRh5cJc9gn8412fb4QZM8th+Gd7zx2mhoeALU3w3pkFa524MnCxuy/AJRAjFYar7X7FHatJhusBq1ydi9sIhfV14vdUiaj3AXFVH5+jAA7vjterC2L9TvOgCoNXdyEzcWbpu7yhDcnHXx5vDOyewAo5Or/X0uRfSHJQO4yJQ0Rq5Haxuz9HxLV29zTuonMyoVBtrR9U2QKnk5Malz1tn5lI5/7tPwqh3+Lmmxzr52MDZnY11zQ/rwnGIrmNVwPcnXwmzZqdXQpTivMqg0dTI5JCUEzcZwyysyWjWL9MKa3XqllzG25zlkpODdQPX+XXDkwv+eAcv5ugN2FF8OWtyUxTwpQADT0C5JT6ubgd29CdZyf+YcMKUCE9zwHiAbSh1NodDi2R+Q8TbR+O/pPhg2YEnOQOHuhQuwLV2990c9ml5WhLE1eF1x1ZnMfRYnqDXdaqMvwTAxTM+f9lMc9JsOS3bgfOA6eKgyG+bEG/FyxiQL2Lx6km68qHGOSZHPHLBaOxRbw2IuObZ/P4VOXJWZE=
  app: ricardoiorin
  on:
    repo: NicoRomero3210/SwIC
