language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install:
- npm install express mocha supertest chai
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: ma+YIHXYhz5FBOAQYwsfbl/Nl2hZ/XmN4aSHzCGlI0v3DoW3kY+VhLphenfRztr08od93c+twqMYjKFb2t/PjRhL/ynWmRPvPYv23CdRSXgKoQD/VWwAArMyX9PnYCddYwXzTM2d6cAClEK501CgRaQEKEfu3BXIlp0g0PNYlRpjBjjF3ND9NTtfWPT2xaQZm2Tz3vMwRqgQtfTWGopf8CGztpvueE6n4s0/bW9kV07Fb3rXR11ZFfP1b6oU5WC73pGzYmXD518m1pscA/qNaAPc7bqgR8r9rIJT4GxuF87JgEnsWSrIIfGWqh/jvHIIz5jOFcTfbhmCcngLgdccg5ti2jEffbpmSTwYer8i93PoIBetvWfO5BEHSrUmfxBdjSr+BlBia0mJhHVPqrUqtJtgL73qENX+frR88uVxu5fgnC2/UB7zg7RHRtnQtY8/gvssmVQ0RUhvkc92Ex9Eun6SWsx+M9TaIcyzRuRHSCklLOysdyFl+uhMfyjUxVHGCuyAtGqtAqIZw7blJmdZFclZlNAu61QPoauqMgLMsPbboO/8Xqmlrakq/kmu8SiMqKy17pma6U4luEOWQY8vpJOg1B3MCE/KjbTgBk94d6bfKW9G19u1LlZOkcCXdFsDs7JBlB3KgLqlRbHDPQrd38/uduZu+Y4WW5AibAAtBPI=
  app: ricardoiorin
  on:
    repo: NicoRomero3210/SwIC
