language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install:
- npm install express mocha supertest chai
script:
- npm run test
deploy:
  provider: heroku
  skip_cleanup: true
  app: ricardoiorin
  on:
    repo: NicoRomero3210/SwIC
  api_key:
    secure: ev1JVh87tIrFvBmnRm2YFj9uzHu86C/s7j/1p+Ck+ER0JeDdEmsb7D35axcqA2xwIK4uS7Z8JRvEA2Q/GEqfdp5/NnADuv6IFmIJ2ZGCeeuEGjt3krM0orzttnJhqx6KuL4bi4eB2ODsHqCeisv77BRg3DUhN1XDJhSg5VM5LOrzadUAHEpVm37sPBKFTupVtDgvwRpRXC7rCfnHSt7jx/VNO9K6wHVSwQYsQdFm557UEVLQ5L2sXuhpyUllBnC0c32va+3Q/DisojxbDclvkT/BiWL7dghuYmoXNcrnc3TEHJVLJd97Dw6JRonCy44I5BdkbjbXpPl4LJU33LHPRfFydcXEMxaIg9ZEuMuEbKWij68jETz5OT4belCRLj2oAEpVp/cOOJuUyc7yBbdODU3WytWU1xiLDRvhOEvojMw3CISqSfb8hik2mWubnvZkA9zMsdWS+LifmwpT8AntuHUVJAaUn9VQ1SMmQ7TV1DRs/TwsyHbGC5gfwVnHtBEVEWhDn3vPJ+ced/ipO35jEn26AhFlBu8mUn9acaYbSh8xlPS6T5lSq/7aWqzTF32LQEJ/Us06MYRZIkJFrpyOqKGV+2Z4/hXQLCAA+oavvtGakph9RRrFZUfQ/s7mrcGQPfmxjFaAvx0RNWa06dVTLyoHnazLeE5WT8p8aN3UgfA=
