language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install:
- npm install express mocha supertest chai
script:
- npm run test
deploy:
  provider: heroku
  skip_cleanup: true
  app: ricardoiorin
  on:
    repo: NicoRomero3210/SwIC
env:
  global:
    secure: qKoCVWi40R038j3uIE2Y8BIkKWwf9nT69NP+bs0atu39bCuQWMAMPlMyOHui+yhGhsLoy18SqfZhlOSvffAaW3Bo2sQOB0NDGRKBWzcc0GH+p4e8Bd8bJRLiVDXUiBhXTS3Z+9SBB39O2/5YmDTytsz1F67ZCcMPnhx1S25aXONaH86KCrCbgUzl/G5BUlGYD2TZaRb0LtpCUhX5+no23bL7MoIlLzCDoaIs6wntadnpzWjwDk8UpuF+E90C0UDzF4vxMmrQFLe3A/VjyRYGcmMhNBSqLq7LlWJJXI+yvD/5dQL69G911YnYTK57wYFlHgJsRm/qReolmpp3x5cBOAJI6sq+CoHQW6ltn97CRWal7tAxqJYrxNVdcLMcxl0KQtRh71L1uNgVESQB7alckXUvjQ1giSggDjRSd+XQAes5Y0kwN3xO+XOqBX+6n9HPxtibmJea0qOCCEaxg2/1RmySXbRMVm72fbbBaVoTSp+t8J6KsDjjZhidJd9lyzY2UxeAOotc0mIA+CjfsCYazk4b4zyjEW5PpmXsDApmhV2EDG9SJhA7W4pgH8rAGcXgWMU/aYwdc9x/cPwtyvNGMXXRMZqQ9uzpKJis3axew6Z0JoBxHQWICbezE5JdpcasHU9m75FUfa9CHCbCQwz94GvREni2nSwVouQ9z7r0N5s=
