language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install:
- npm install express mocha supertest chai
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: wMJdy1SPxyPnC8fBpRZ/DJlNAf0UOK3p8aywX/26DL/pAsXADIzl3Oo4a9osFOa3lLvrDsIDIbs2W/GHDuf98/Tn49vyjmeQSJFjIzrVaQx8qU/NLhE4H2v1pEsCOqLILZKOQMfwtipvfaB5fztjtX9ZLH9YEve90j0pWOerVB0kfh3Jo9tqC9x3XRZTBIFfTG2mfhlVJioG7FWVT5onlWU8sSBEggPzX4M5vVecFAG7kGDGKHOUINAKmH6IcIOk5PzBP/4MavEyl0OLCbZd7ARKWql8ErKgDdrPjnILqZP2Su3yUYHROkZ+6oagpmCDHecoalDjMe/v6S4v5saUWYg/R5HHCdQaecrNa2sEcHAJd+sjIle+KcZ8vgIfLhyI714KjhJt/oUmunS23zun55wloCOy+4T1hkcLPZC92s1G43hEp/okktRCSfp4TrIplzckUQL9SfNgsZgrhUEaCDPLxomNEUMXX4aVfEjTusD9/Y9nv69cfZTRTvwXVG9qze5GBJkQ1c0dt+sp4mNiWQ8Kq247SLqahOEa+uqidKNwpzUW79wXHKgMIdmWtGmR+vvb/XhhxaTdepRY7Wzi5cG6Gm4l4e3CTug9YJkW1TAKhQbk2vOeWbbKhaHyWGHWVU1x2TbhSDgp0HslfnLXaON5kNRF9hvRS8mjowtCum8=
  app: ricardoiorin
  on:
    repo: NicoRomero3210/SwIC
